name: Build and Release APK

on: [push] # Trigger on push to the default branch (e.g., main, master)

jobs:
  build_and_release:
    runs-on: ubuntu-latest # Use Ubuntu for building

    steps:
      - uses: actions/checkout@v2 # Checkout your repository code
      - name: Set up JDK 11 # Set up a compatible Java version
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # Or your preferred distribution
          java-version: 11
      - name: Generate release APK # Build the release APK
        run: ./gradlew assembleRelease
      - name: Create Release on GitHub # Create a new release with the APK
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }} # Use the commit SHA as the tag
          release_name: Release ${{ github.sha }}
          draft: false # Set to true to make the release a draft
          prerelease: false # Set to true for a prerelease
          body: "New release" # Release description

      - name: Upload APK to release
        uses: actions/upload-release-artifact@v1
        with:
          upload_url: ${{ github.ref_type == 'tag' && github.ref }} # Replace with the actual upload URL
          file: app/build/outputs/apk/release/app-release.apk # Path to your release APK
          tag_name: ${{ github.sha }}
          label: APK Release # Optional label